fileVersion: 1
id: "85"
mappingDefinitions:
  SAMPLE:
    database: ""
    schema: ""
  TEST:
    database: ""
    schema: ""
  WORK:
    database: test
    schema: ""
name: New Environment
type: Environment
