fileVersion: 1
id: "85"
mappingDefinitions:
  MIGRATION_TARGET:
    database: ""
    schema: ""
  SAMPLE:
    database: ""
    schema: ""
  WORK:
    database: test
    schema: ""
name: New Environment
type: Environment
